### ISSUE TITLE
Doesn't account for an all negative array.

### ISSUE THREAD

**Issue by wley3337** [learn-co-curriculum/largest-subarray-sum#2]
The current solution doesn't account for an all negative array. 
This should work: 
function largestSubarraySum(array) {
    let ans = 0;
    let sum = 0;
    for (var i = 0; i < array.length; i++) {
        ans = Math.max(0, ans + array[i]);
        sum = Math.max(sum, ans);
    }
   return  array.sort((a,b)=> a-b)[array.length -1] < 0 ?
   array.sort((a,b)=> a-b)[array.length -1] :
    sum;
};

**Comment by wley3337** [comment]
function largestSubarraySum(array) {
    let ans = 0;
    let sum = 0;
    for (var i = 0; i < array.length; i++) {
        ans = Math.max(0, ans + array[i]);
        sum = Math.max(sum, ans);
    }
   return  array.sort((a,b)=> a-b)[array.length -1] < 0 ?
   array.sort((a,b)=> a-b)[array.length -1] :
    sum;
};

**Comment by rrcobb** [comment]
Closing - max subarray for an all-negative array is `[]`, with sum 0.
