### ISSUE TITLE
Largest subarray sum of an array of all negative numbers is 0?

### ISSUE THREAD

**Issue by IgoVeyner** [learn-co-curriculum/largest-subarray-sum#4]
I really don't follow the logic for the test on line 37 in index-test.js.
The array is [-1, -1, -5, -3, -7, -4, -5, -6, -100, -4]
And the expected return value is 0

How exactly does the sum of any of these numbers add up to 0? 

Or is it just a special case you are testing for - if the sum ends up to be negative please return 0? 
If so please state that in the readme! Otherwise this test case does not make any sense!! 

The expected return value would either be -1 (the largest value in the array / if you allow a subarray sum of length 1) or -2 (the sum of the largest two contiguous numbers in the array).

**Comment by graciemcguire** [comment]
Hey @IgoVeyner!
Often times in algorithmic problems, we need to look at the tests to find hints that aren't explicitly given to us in the instructions. With a case like this, giving a default value of 0 if the sum is less than 1 would be a great place to start.
You will often find problems that don't allow for a negative return value as you work through different code problems.

Thanks for raising this issue, and happy coding!
